"""GitHub Markdown formatting for magicreview reports."""

from __future__ import annotations

from typing import Any

from app.report.cli_formatters import normalize_result


SUMMARY_MARKER = "<!-- magicreview-summary -->"


def inline_marker(issue: dict[str, Any]) -> str:
    return f"<!-- magicreview-inline:{issue['type']}:{issue['file']}:{issue['line']} -->"


def format_summary_comment(result: dict[str, Any], *, errors: list[str] | None = None) -> str:
    normalized = normalize_result(result)
    summary = normalized["summary"]
    top_issues = normalized["issues"][:10]
    metadata = result.get("metadata", {}) if isinstance(result.get("metadata", {}), dict) else {}
    review_mode = metadata.get("review_mode")
    lines = [
        SUMMARY_MARKER,
        "## MagicReview Report",
        "",
    ]
    if review_mode:
        lines.extend([f"Review mode: `{review_mode}`", ""])
    lines.extend([
        "Summary:",
        f"- Critical: {summary['critical']}",
        f"- High: {summary['high']}",
        f"- Medium: {summary['medium']}",
        f"- Low: {summary['low']}",
        "",
        "Top Issues:",
    ])
    if top_issues:
        for index, issue in enumerate(top_issues, start=1):
            lines.append(f"{index}. [{str(issue['severity']).upper()}] {issue['type']} - {issue['file']}:{issue['line']}")
    else:
        lines.append("No issues found.")
    if errors:
        lines.extend(["", "Processing Notes:"])
        lines.extend(f"- {error}" for error in errors)
    lines.extend(["", "Generated by MagicReview."])
    return "\n".join(lines)


def format_inline_comment(issue: dict[str, Any]) -> str:
    return "\n".join(
        [
            inline_marker(issue),
            f"[{str(issue['severity']).upper()}] {issue['type']}",
            "",
            str(issue["message"]),
            "",
            "Suggestion:",
            str(issue["suggestion"]),
        ]
    )
